#!/bin/sh
xset s off -dpms 2>/dev/null &
if [ -f /usr/share/mitraos/wallpaper.jpg ] && command -v feh >/dev/null 2>&1; then
    feh --bg-fill /usr/share/mitraos/wallpaper.jpg &
fi
/usr/bin/mitra-dock-daemon &
while true; do
    jwm
    sleep 1
done
